### ISSUE TITLE
Stop serving empty css file

### ISSUE THREAD

**Issue by FaridAghili** [manmohanjit/nova-belongs-to-dependency#10]
In file https://github.com/manmohanjit/nova-belongs-to-dependency/blob/master/src/FieldServiceProvider.php line 20 can be removed as there is no css style used in this package.

**Comment by RVxLab** [comment]
@FaridAghili As this package seems abandoned we forked it and addressed this issue in there. See https://github.com/webparking/nova-belongs-to-dependency

**Comment by FaridAghili** [comment]
@RVxLab Thanks, I'll try that for sure.
