### ISSUE TITLE
list the items related to the master category->searchable

### ISSUE THREAD

**Issue by niltonmelox** [manmohanjit/nova-belongs-to-dependency#2]
Hi everyone, I need a help on using, for example: I have a category and a subcategory, the subcategory should list the items related to the master category.

**Comment by manmohanjit** [comment]
Hello Nilton, this section is for issues only. To look for usage examples please refer to the README.md file.

For your usage, you could do something like this on your Post resource:
```
use Manmohanjit\BelongsToDependency\BelongsToDependency;
...
return [
    ...
    BelongsTo::make('Category'),
    
    BelongsToDependency::make('Sub Category')
        ->dependsOn('type', 'category_id'),
    ...
];
```

Table structure:
category (id, name)
sub_category (id, name, category_id)

Thanks.
