### ISSUE TITLE
Not filtering before "parent" BelongsTo has changed

### ISSUE THREAD

**Issue by simonedelmann** [manmohanjit/nova-belongs-to-dependency#4]
Hi,
I just found your package and immediately updated from orlyapps/nova-belongsto-depend.
Great work! Your solution is much more clean.

There is just one thing:
If I edit a model, I need to change the parent BelongsTo first before my BelongsToDependency field gets filtered options.
As an example imagine, I would have implemented the structure from the README (type, posts, category). If I edit a post, I can now select all categories, no matter which type. I have to change the type at least once before only the correct categories will display.

**Comment by manmohanjit** [comment]
Hey there,

I will look into this.

Thanks!

**Comment by simonedelmann** [comment]
Hi @manmohanjit 

I did some investigation here. Although I'm not absolutely sure what causes the problem, I've found a workaround. I will describe exactly what I've done:

**Setup**
Fresh Laravel + Nova

I've created three models: project, task and user:
- Each project has many tasks and many users.
- Each task belongs to a project and has many users.
- Each user belongs to a project and task (depending on the project). For this relationship I use this package.

**The problem**
When I edit an user and I click on the tasks select, all tasks from all projects are displayed. 

**What should be?**
Only the tasks from the user's project should be displayed initially. 
(The "filtering" works as expected when I change the project at least once. But on edit it should already work initially.)

**What did I do to solve the problem?**
I did some debugging and I tried some things. Calling `this.initializeComponent()` twice within 
`dependencyWatcher()` solves the problem. I don't really understand why it is working that way, but not somehow else! Maybe you can find a cleaner solution.

```
dependencyWatcher(value) {
    if(value === this.dependsOnValue) {
        return
    }

    this.dependsOnValue = value

    this.clearSelection()
    this.initializeComponent()
    this.initializeComponent()   // added
}
```

I will send a PR with this change in a minute.

**Comment by simonedelmann** [comment]
Hi @manmohanjit,
is there any chance to get the PR for this merged?
Thanks!

**Comment by alberto-bottarini** [comment]
I fixed using another approach, to avoid 2 http requests:

https://github.com/manmohanjit/nova-belongs-to-dependency/pull/8
